server:
  port: 8083
spring:
  application:
    name: NotificationService
  kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      consumer:
        group-id: ${KAFKA_GROUP_ID}
        auto-offset-reset: earliest
        enable-auto-commit: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

