spring:
  application:
    name: OrderService
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      url: ${POSTGRES_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCE_SERVER_JWT_ISSUER}
server:
    port: 8085


service:
  product:
    url: http://localhost:8081
  cart:
    url: http://localhost:8082
